### ISSUE TITLE
Setting same "value" forcefully select all the applicable "displays "

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#208]
How can we set them to have same values but not being selected together for display purpose?

These 3 should have same value, 3 in order to be used for computing later to create score.
<img width="1183" alt="スクリーンショット 2021-10-12 16 00 45" src="https://user-images.githubusercontent.com/61481039/136907785-30c09e98-ae8b-48fc-a035-d6ab9b31de1d.png">
<br>
<br>
But setting them so forces users to choose all the applicable choices if they choose any of 3
<img width="928" alt="スクリーンショット 2021-10-12 16 01 22" src="https://user-images.githubusercontent.com/61481039/136907920-2a82736c-78ac-4bc5-a998-7aa453dcd5ff.png">

**Comment by Show-M** [comment]
This is a blocking issue.

**Comment by Show-M** [comment]
@rgagne   
Please work in this. This is a blocking issue for #210 ...

**Comment by rgagne** [comment]
I can fix the multi select but that will still leave the problem that choosing any of those items will result in the same value stored = 3. That means if someone were look at it later then it would default to the first item even if the user chose the last item.

Added support for using number like symbols

make the options 1, 2, 3a, 3b, 3c and then wrap the value with `integer` like below. Only use `integer` where needed because it is an expensive call.

```
{integer(values.test1) + integer(values.test2) + values.test3}
```

**Comment by Show-M** [comment]
@rgagne 
added. https://web.weave.io/634f007d-8fdf-45e4-b3a0-6d3a61cf04f5/stream/~/p0

**Comment by Show-M** [comment]
I guess somewhere like {}() are wrong...?
<img width="1148" alt="スクリーンショット 2021-12-07 23 08 23" src="https://user-images.githubusercontent.com/61481039/145044078-37ba8b4f-5d9b-482a-af79-cbb66a00c08d.png">
